### ISSUE TITLE
Kip's feedback checklist

### ISSUE THREAD

**Issue by querkmachine** [BristolFurs/bristolfurs-website#8]
Tech/code-y changes requested. Content changes are not included here.

- [ ] Add PDF version of code of conduct.
  - Worth a chat maybe, not sure how useful this is to a layperson, probably not very.
- [x] Add @querkmachine to the team page somewhere .
- [x] Add Ko-Fi embed to the support page (probably need someone else to snag the embed code).
- [x] Add FAQs to main navigation.
- [x] Fix fursuiting button link on homepage 404ing.
- [x] Remove references to Twitter. Account is no longer used.
- [ ] Add some mechanism to the homepage for important updates and announcements.
  - Could use clarification on requirements. Emergency banner already exists for important updates. If meaning some kind of blog-like functionality, I'm not terribly sure how useful that is unless it's being updated semi-regularly with substantial content (i.e. paragraphs rather than sentences).
